/*
 * esc_main.h
 *  Created on: Sep 20, 2025
 *      Author: joaoh
 *
 *  High-level ESC application wiring. Declares the initialization and
 *  background loop functions plus the TIM1 handle shared with the HAL
 *  callbacks.
 */

#ifndef INC_ESC_MAIN_H_
#define INC_ESC_MAIN_H_

#include "stm32g4xx_hal.h"

/// Initialize ESC application (drivers, timers, wiring).
void ESC_Main_Init(void);

/// Main loop hook for background tasks (CLI, telemetry, etc.).
void ESC_Main_Loop(void);

/// TIM1 handle (generated by CubeMX in main.c).
extern TIM_HandleTypeDef htim1;

#endif /* INC_ESC_MAIN_H_ */
