/*
 * esc_api.h
 *  Created on: Sep 20, 2025
 *      Author: joaoh
 *
 *  C-friendly entry points used by the autogenerated CubeMX code.
 *  They forward into the C++ ESC application that wires together
 *  the motor, driver, and sensor layers.
 */

#ifndef INC_ESC_API_H_
#define INC_ESC_API_H_

#ifdef __cplusplus
extern "C" {
#endif

/// Initialize the ESC application (called from main()).
void ESC_Main_Init(void);

/// Background application loop (invoked from the super-loop).
void ESC_Main_Loop(void);

#ifdef __cplusplus
}
#endif

#endif /* INC_ESC_API_H_ */
